services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: npm start

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
